slims:
  # Ask your IT people for credentials (Remember to say please)
  url: 'http://slims.example.com/slimsrest'
  username: apiusername
  password: apipassword
  # Find sample records with content type 22 (Fastq) and qdrna in the samplesheet decription field
  # Exclude samples explicitly marked as "Do not include"
  find_criteria: |
    cntn_fk_contentType equals 22
    and cntn_cstm_doNotInclude not_equals true
    and cntn_cstm_rawSheetDescription contains qdrna
  # Check for derived records (->) with contentType 23 (Bioinformatics) and complete secondary analysis state
  check_criteria: |
    -> cntn_fk_contentType equals 23
    and cntn_cstm_SecondaryAnalysisState equals complete
  # Get file path from slims (unless specified in samples file)
  # Add backup remote keys for HCP hook
  # Add run information to samples
  map:
    - files=json:cntn_cstm_demuxerSampleResult.fastq_paths
      run=cntn_cstm_runTag
      backup=json:cntn_cstm_demuxerBackupSampleResult.remote_keys
  # Create derived records with content type = 23 (Bioinformatics)
  # Include state from cellophane sample (access key using curly braces)
  # Other parameters are required by SLIMS or records will not be created
  derive:
    - cntn_fk_contentType=23
      cntn_fk_location=83
      cntn_cstm_SecondaryAnalysisState={state}
      cntn_status=10