required:
  - rsync
properties:
  rsync:
    type: object
    required:
      - base
    properties:
      overwrite:
        type: boolean
        description: Overwrite existing results
        default: false
      large_file_threshold:
        type: string
        description: Files larger than this will be copied in a separate job (eg. 100M, 1 GB)
        default: "100M"
