type: object
properties:
  rsync:
    type: object
    required:
      - base
    properties:
      skip:
        type: skip
        default: false
        description: "Don't rsync results"
      base:
        type: path
        description: Base of directory where results will be stored
      overwrite:
        type: boolean
        description: Overwrite existing results
        default: false
      large_file_threshold:
        type: string
        description: Files larger than this will be copied in a separate job (eg. 100M, 1 GB)
        default: "100M"
