type: object
properties:
  unpack:
    type: object
    properties:
      init:
        type: string
        description: Code to run before unpacking (Bash)
      exit:
        type: string
        description: Code to run after unpacking (Bash)
      threads:
        type: integer
        description: Threads for decompression
        default: 40
