type: object
properties:
  unpack:
    type: object
    properties:
      sge_queue:
        type: string
        description: SGE queue for decompression
      sge_pe:
        type: string
        description: SGE parallel environment for decompression
      sge_slots:
        type: integer
        description: SGE slots (threads) for decompression
        default: 40
    required:
      - sge_queue
      - sge_pe
