name: Push modules to branches
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push modules to branches
    strategy:
      matrix:
        module: [hcp, slims]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      
      env:
        REPO: self
        BRANCH: ${{ matrix.module }}
        FOLDER: ${{ matrix.module }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
