name: Push modules to branches
on:
  push:
    branches:
      - main
      - dev
  release:
    types:
      - published


jobs:
  deploy:
    strategy:
      matrix:
        module: [hcp, slims, unpack, nextflow, rsync, mail]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ matrix.module }}

    - uses: s0/git-publish-subdir-action@develop
      if: ${{ github.ref_name == 'main' }}
      env:
        REPO: self
        BRANCH: ${{ matrix.module }}
        FOLDER: ${{ matrix.module }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_EMPTY_COMMITS: true
        MESSAGE: "Update to {sha}: {msg}"
    
    - uses: s0/git-publish-subdir-action@develop
      if: ${{ github.ref_name != 'main' }}
      env:
        REPO: self
        BRANCH: ${{ matrix.module }}_${{ github.ref_name }}
        FOLDER: ${{ matrix.module }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_EMPTY_COMMITS: true
        MESSAGE: "Update to {sha}: {msg}"
