on:
  workflow_call:
    inputs:
      module:
        description: The name of the module
        type: string
        required: true
      path:
        description: The working directory (must contain pyproject.toml)
        type: string
        required: true
      version:
        description: The version to pass to 'poetry version'
        type: string
        default: ""
      head:
        description: The branch or tag to checkout
        type: string
        required: true

jobs:
  sync-poetry:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}
      - name: install-poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
          cache-dependency-path: ${{ inputs.path }}/poetry.lock
      - name: poetry-version
        run: poetry version -- ${{ inputs.version }}
      - name: poetry-lock
        run: poetry lock
      - name: poetry-export
        run: |
          poetry export \
            --format=requirements.txt \
            --output requirements.txt \
            --without-hashes \
            --without-urls
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.module }}-poetry-files
          path: |
            ${{ inputs.path }}/pyproject.toml
            ${{ inputs.path }}/poetry.lock
            ${{ inputs.path }}/requirements.txt
