# Move non-release PRs to dev branch
---
name: Update PR

permissions:
  checks: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  workflow_run:
    workflows: [PR Open/Edit]
    types:
    - completed

concurrency:
  group: ${{ github.workflow }}

jobs:
  pr-metadata:
    name: Fetch PR metadata
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.pr-metadata.outputs.pr_number  }}
      pr-head-sha: ${{ steps.pr-metadata.outputs.pr_head_sha  }}
      lables-add: ${{ steps.pr-metadata.outputs.pr_lables_add  }}
      labels-remove: ${{ steps.pr-metadata.outputs.pr_labels_remove  }}
    steps:
    - uses: dawidd6/action-download-artifact@v7
      with:
        name: pr-metadata
        run_id: ${{ github.event.workflow_run.id }}
    - name: PR Metadata
      id: pr-metadata
      run: |
        echo 'pr_number<<EOF' >> "$GITHUB_OUTPUT"
        cat pr.number >> "$GITHUB_OUTPUT"
        echo 'EOF' >> "$GITHUB_OUTPUT"

        echo 'pr_head_sha<<EOF' >> "$GITHUB_OUTPUT"
        cat pr.head-sha >> "$GITHUB_OUTPUT"
        echo 'EOF'>> "$GITHUB_OUTPUT"

        echo 'pr_lables_add<<EOF' >> "$GITHUB_OUTPUT"
        cat pr.labels.add >> "$GITHUB_OUTPUT"
        echo 'EOF'>> "$GITHUB_OUTPUT"

        echo 'pr_labels_remove<<EOF' >> "$GITHUB_OUTPUT"
        cat pr.labels.remove >> "$GITHUB_OUTPUT"
        echo 'EOF'>> "$GITHUB_OUTPUT"

  tag-pr:
    name: Add tags
    runs-on: ubuntu-latest
    needs: pr-metadata
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ !env.ACT }}
      with:
        number: ${{ needs.pr-metadata.outputs.pr-number }}
        labels: |
          ${{ needs.pr-metadata.outputs.lables-add }}

    - uses: actions-ecosystem/action-remove-labels@v1
      if: ${{ !env.ACT }}
      with:
        number: ${{ needs.pr-metadata.outputs.pr-number }}
        labels: |
          ${{ needs.pr-metadata.outputs.labels-remove }}

  publish-pytest-results:
    runs-on: ubuntu-latest
    needs: pr-metadata
    steps:
    - uses: dawidd6/action-download-artifact@v7
      with:
        name: '.*\.pytest\.xml'
        name_is_regexp: true
        run_id: ${{ github.event.workflow_run.id }}
    - name: Merge reports
      run: |
        npx --package=junit-report-merger -c 'jrm merged-dev.xml */*-dev.pytest.xml'
        npx --package=junit-report-merger -c 'jrm merged-latest.xml */*-latest.pytest.xml'
    - uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!github.event.act)
      with:
        check_name: Test Results (cellophane@latest)
        files: merged-latest.xml
        commit: ${{ needs.pr-metadata.outputs.pr-head-sha }}
    - uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!github.event.act)
      with:
        check_name: Test Results (cellophane@dev)
        files: merged-dev.xml
        commit: ${{ needs.pr-metadata.outputs.pr-head-sha }}
