# Move non-release PRs to dev branch
---
name: PR Open/Edit

permissions:
  checks: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}

jobs:
  modules:
    name: Modules
    uses: ./.github/workflows/def_list-modules.yml

  pr-metadata:
    runs-on: ubuntu-latest
    name: Upload PR metadata
    needs: [modules]
    steps:
    - name: PR Metadata
      run: |
        yq '.[].name' <<< "${{ needs.modules.outputs.changed_modules }}" | tee "pr.labels.add"
        yq '.[].name' <<< "${{ needs.modules.outputs.unchanged_modules }}" | tee "pr.labels.remove"
        echo ${{ github.event.pull_request.number }} | tee "pr.number"
        echo ${{ github.event.pull_request.head.sha  }} | tee "pr.head-sha"

    - uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        name: pr-metadata
        path: pr.*


  pytest-latest:
    uses: ./.github/workflows/def_pytest.yml
    needs: modules
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        include: ${{ fromJson(needs.modules.outputs.changed_modules) }}
    with:
      pr-head-sha: ${{ github.event.pull_request.head.sha }}
      module: ${{ matrix.name }}
      path: ${{ matrix.path }}
      version: ${{ github.event.pull_request.head.sha }}
      cellophane-repo: ClinicalGenomicsGBG/cellophane
      cellophane-tag: latest
      check-fail: true

  pytest-dev:
    uses: ./.github/workflows/def_pytest.yml
    needs: modules
    permissions:
      checks: write
      pull-requests: write
    strategy:
      matrix:
        include: ${{ fromJson(needs.modules.outputs.changed_modules) }}
    with:
      pr-head-sha: ${{ github.event.pull_request.head.sha }}
      module: ${{ matrix.name }}
      path: ${{ matrix.path }}
      version: ${{ github.event.pull_request.head.sha }}
      cellophane-repo: ClinicalGenomicsGBG/cellophane
      cellophane-tag: dev
      check-fail: true

  reviewdog-lint:
    name: Lint code
    uses: ./.github/workflows/def_reviewdog-lint.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}-reviewdog-lint
    with:
      head: ${{ github.event.pull_request.head.sha }}
