---
name: Push to main

permissions: read-all

on: # yamllint disable-line rule:truthy
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}

jobs:
  cellophane-releases:
    name: Cellophane releases
    uses: ./.github/workflows/def_list-releases.yml
    with:
      repo: ClinicalGenomicsGBG/cellophane

  modules:
    name: Modules
    uses: ./.github/workflows/def_list-modules.yml
    with:
      has-changes-override-pattern: modules.json

  module-pr:
    name: Create or update release PR
    uses: ./.github/workflows/def_module-pr.yml
    needs: [modules, cellophane-releases]
    if: needs.modules.outputs.modules != '[]'
    permissions:
      pull-requests: write
      contents: write
      checks: write
      issues: write
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.modules.outputs.modules) }}
    with:
      module: ${{ matrix.name }}
      path: ${{ matrix.path }}
      has-changes: ${{ matrix.has-changes }}
      base: main
      head: ${{ github.event.ref }}
      cellophane-repo: ClinicalGenomicsGBG/cellophane
      cellophane-releases: ${{ needs.cellophane-releases.outputs.releases }}

  cleanup:
    name: Cleanup artifacts
    needs: module-pr
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: "*"
