name: Remove module branches for deleted tags
on:
  release:
    types:
      - deleted
      - unpublished 

jobs:
  delete_branches:
    strategy:
      matrix:
        module: [hcp, slims, unpack, nextflow, rsync, mail]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ matrix.module }}_${{ github.ref_name }}

